### ISSUE TITLE
When using Docker Compose, `influxdb`'s `external_port` should be 8086, not 28086, in `config.yaml`

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#101]
@hyokyungk 한 번 확인해 주시면 감사하겠습니다. 😊

**What happened**
: 
[CB-DF README](https://github.com/cloud-barista/cb-dragonfly/blob/master/README.md) 에 나와 있는 대로
`conf/config.yaml 파일` 파일에서
`   influxdb:` 아래의 `external_port:` 의 값이 `28086` 인 상태에서

```yaml
   # influxdb connection info
   influxdb:
     endpoint_url: http://cb-dragonfly-influxdb           # endpoint for influxDB
     internal_port: 8086
     external_port: 28086
```

`sudo make compose-up` 을 실행하면

cb-dragonfly 가 `http://cb-dragonfly-influxdb:28086` 핑에 실패하여 cb-dragonfly 컨테이너가 계속 종료&재시작됨

```
 tcp 172.18.0.4:28086: connect: connection refused 
panic: Get "http://cb-dragonfly-influxdb:28086/ping?wait_for_leader=5s": dial tcp 172.18.0.4:28086: connect: connection refused

[CLOUD-BARISTA].[ERROR]: 2021-07-06 16:06:09 influxdb.go:63, github.com/cloud-barista/cb-dragonfly/pkg/metricstore/influxdb/v1.Storage.Initialize() - failed to ping InfluxDB, error=Get "http://cb-dragonfly-influxdb:28086/ping?wait_for_leader=5s": dial tcp 172.18.0.4:28086: connect: connection refused 
[CLOUD-BARISTA].[ERROR]: 2021-07-06 16:06:09 main.go:84, main.main() - failed to initialize influxDB, error=Get "http://cb-dragonfly-influxdb:28086/ping?wait_for_leader=5s": dialmain.main()
        /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/main/main.go:85 +0x5d0
time="2021-07-06T16:06:21+09:00" level=info msg="create tick file with name default.tick"
panic: Get "http://cb-dragonfly-influxdb:28086/ping?wait_for_leader=5s": dial tcp 172.18.0.4:28086: connect: connection refused

goroutine 1 [running]:
main.main()
        /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/main/main.go:85 +0x5d0
time="2021-07-06T16:06:37+09:00" level=info msg="create tick file with name default.tick"
[CLOUD-BARISTA].[ERROR]: 2021-07-06 16:06:37 influxdb.go:63, github.com/cloud-barista/cb-dragonfly/pkg/metricstore/influxdb/v1.Storage.Initialize() - failed to ping InfluxDB, error=Get "http://cb-dragonfly-influxdb:28086/ping?wait_for_leader=5s": dial tcp 172.18.0.4:28086: connect: connection refused 
[CLOUD-BARISTA].[ERROR]: 2021-07-06 16:06:37 main.go:84, main.main() - failed to initialize influxDB, error=Get "http://cb-dragonfly-influxdb:28086/ping?wait_for_leader=5s": dial tcp 172.18.0.4:28086: connect: connection refused 
panic: Get "http://cb-dragonfly-influxdb:28086/ping?wait_for_leader=5s": dial tcp 172.18.0.4:28086: connect: connection refused

goroutine 1 [running]:
main.main()
        /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/main/main.go:85 +0x5d0
```

---

`external_port:` 값을 `8086` 으로 수정하고

```yaml
influxdb:
  endpoint_url: http://cb-dragonfly-influxdb       # endpoint for influxDB
  internal_port: 8086
  external_port: 8086
```

`sudo make compose-up` 을 실행하면
cb-dragonfly 가 문제 없이 실행됨

```
❯ docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                                NAMES
bddbb7a12a89        chronograf:1.8.4-alpine                            "/entrypoint.sh --in…"   20 minutes ago      Up 12 minutes       0.0.0.0:8888->8888/tcp                               cb-dragonfly-chronograf
5ead5c5eeb27        cloudbaristaorg/cb-dragonfly:espresso-v0.1-kafka   "cb-dragonfly"           20 minutes ago      Up 12 minutes       0.0.0.0:9090->9090/tcp, 0.0.0.0:9999->9999/tcp       cb-dragonfly
e9af6eeb1a2b        kapacitor:1.5                                      "/entrypoint.sh kapa…"   20 minutes ago      Up 12 minutes       0.0.0.0:29092->9092/tcp                              cb-dragonfly-kapacitor
d944b857e45d        influxdb:1.8-alpine                                "/entrypoint.sh infl…"   20 minutes ago      Up 12 minutes       0.0.0.0:28086->8086/tcp, 0.0.0.0:28088->8088/tcp     cb-dragonfly-influxdb
f932dde06d05        wurstmeister/kafka:2.12-2.4.1                      "start-kafka.sh"         29 minutes ago      Up 12 minutes       0.0.0.0:9092->9092/tcp                               cb-dragonfly-kafka
09f05fec263d        wurstmeister/zookeeper                             "/bin/sh -c '/usr/sb…"   29 minutes ago      Up 12 minutes       22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   cb-dragonfly-zookeeper
```

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

(안)
CB-Dragonfly 가
Docker Compose 모드, Helm chart 모드 등으로 실행될 때에는
`config.yaml` 의
`external_port:` 의 값을 읽지 않고
`internal_port:` 의 값을 읽도록 수정

**Any other context**
:

`cb-operator` repo 안에 있는
`cb-dragonfly` 의 `config.yaml` 에 대해서는
`external_port:` 의 값을 `28086` 에서 `8086` 으로 수정했음

[cb-operator]
- Docker Compose mode: https://github.com/cloud-barista/cb-operator/commit/ca996989fa63a5ef5fdcb78424a3f6367b7b23d3
- K8s mode: https://github.com/cloud-barista/cb-operator/pull/134/files

**Comment by hyokyungk** [comment]
@jihoon-seo 

현재 CB-DF가 구동되면서 kafka에 연결할 때 deploy_type이라는 config 값을 활용하고 있는데,
InfluxDB에서는 해당 내용이 적용이 안되어서 발생하는 이슈인 것 같습니다.

해당 부분은 InfluxDB 연결 시에도 동일한 로직을 추가하도록 하겠습니다.

**Comment by powerkimhub** [comment]
> This repository is being archived, so we’re closing all open issues. 
> Thank you for your contributions.
