### ISSUE TITLE
K8s namespace "dragonfly" is hardcoded in DF

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-dragonfly#129]
**What happened**
: 
https://github.com/cloud-barista/cb-operator/pull/172#issuecomment-978773220

제가 cb-operator에 있는 Cloud-Barista Helm chart를 실행해 봤는데,
DF 파드가 계속 `CrashLoopBackOff` 상태네요..
```
NAME                                                     READY   STATUS             RESTARTS   AGE
cb-dragonfly-5c6cfdb965-d4hl9                            0/1     CrashLoopBackOff   6          13m
cb-dragonfly-influxdb-0                                  1/1     Running            0          13m
cb-dragonfly-kafka-0                                     1/1     Running            1          13m
cb-dragonfly-zookeeper-0                                 1/1     Running            0          13m
cb-mcks-64fbc88ff9-498zv                                 1/1     Running            0          13m
cb-restapigw-786c5789fb-6wcht                            1/1     Running            0          13m
cb-restapigw-influxdb-8494b7858b-x9f5n                   1/1     Running            0          13m
cb-restapigw-jaeger-agent-fw9kz                          1/1     Running            0          13m
cb-restapigw-jaeger-cassandra-schema-zhxfz               0/1     Completed          0          13m
cb-restapigw-jaeger-collector-5955dd767f-mt5d7           1/1     Running            2          13m
cb-restapigw-jaeger-query-547fd7844-5mxpc                2/2     Running            5          13m
cb-restapigw-readonly-85f699b77b-2dnq7                   1/1     Running            0          13m
cb-spider-748cfff964-bklx2                               1/1     Running            0          13m
cb-tumblebug-f9d7dfc64-rv7m5                             1/1     Running            0          13m
cb-tumblebug-mapui-854b567558-wrrt6                      1/1     Running            0          13m
cb-webtool-994b7bc66-qslhh                               1/1     Running            0          13m
cloud-barista-cassandra-0                                1/1     Running            0          13m
cloud-barista-cassandra-1                                1/1     Running            0          10m
cloud-barista-cassandra-2                                1/1     Running            0          8m52s
cloud-barista-dragonfly-kapacitor-5cb786f778-wctj2       1/1     Running            1          13m
cloud-barista-etcd-0                                     1/1     Running            0          13m
cloud-barista-grafana-5fd6c7d4b-tkzdr                    2/2     Running            0          13m
cloud-barista-kube-state-metrics-599fc9945-8nkmm         1/1     Running            0          13m
cloud-barista-prometheus-alertmanager-5f66fd95f5-ch5tx   2/2     Running            0          13m
cloud-barista-prometheus-node-exporter-tqmbw             1/1     Running            0          13m
cloud-barista-prometheus-pushgateway-764b656db6-7r5qb    1/1     Running            0          13m
cloud-barista-prometheus-server-656458bcb9-6tgjv         2/2     Running            0          13m
docker-registry-6f96999dd6-n6b82                         1/1     Running            0          13m
```

DF 파드의 로그는 다음과 같습니다.
```
❯ kubectl logs cb-dragonfly-5c6cfdb965-jdzv4 -n cloud-barista
time="2021-11-25T11:43:30+09:00" level=info msg="create tick file with name default.tick"
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/agent_interval, value:2 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/collector_interval, value:10 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/max_host_count, value:5 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/puller_interval, value:10 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/puller_aggregate_interval, value:30 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/aggregate_type, value:avg 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/deploy_type, value:helm 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/monitoring_policy, value:agentCount 
[CLOUD-BARISTA].[INFO]: 2021-11-25 11:43:30 etcd-driver.go:102, github.com/cloud-barista/cb-store/store-drivers/etcd-driver.(*ETCDDriver).Put() - Key:/monitoring/configs/default_policy, value:push 
[CLOUD-BARISTA].[ERROR]: 2021-11-25 11:43:30 mechanism.go:45, github.com/cloud-barista/cb-dragonfly/pkg/modules/procedure.startPushModule() - failed to initialize collector manager 
panic: configmaps is forbidden: User "system:serviceaccount:cloud-barista:cb-dragonfly" cannot create resource "configmaps" in API group "" in the namespace "dragonfly"

goroutine 1 [running]:
main.main()
        /go/src/github.com/cloud-barista/cb-dragonfly/pkg/main.go:54 +0x2e6
```

DF 코드를 살펴 보니
PR https://github.com/cloud-barista/cb-dragonfly/pull/124 에서
```Go
const (
	Namespace = "dragonfly"
```

코드가 추가되었습니다.

---

CB-Dragonfly repo 내에서 관리하고 계신 CB-Dragonfly Helm chart 에서는
`dragonfly` 라는 K8s 네임스페이스를 사용하시는 것으로 보이는데,

cb-operator repo 내에서 관리하고 있는 CB-Dragonfly Helm chart 에서는
Cloud-Barista와 관련된 대부분의 파드가 `cloud-barista` 라는 K8s 네임스페이스에서 실행되도록 구성되어 있습니다.

따라서, `Namespace = "dragonfly"` 가 DF 소스코드에 하드코딩 되는 것 보다는
다른 방법이 좋을 것 같습니다.
(현재 상태대로는 cb-operator repo 내에서 관리하고 있는 CB-Dragonfly Helm chart 가 정상적으로 작동하지 않습니다.)

@hyokyungk @inno-cloudbarista @devpjh121 검토를 부탁드립니다~~

**What you expected to happen**
: 

**How to reproduce it (as minimally and precisely as possible)**
: 

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by jihoon-seo** [comment]
Resolved by #130
