### ISSUE TITLE
[bug] 최신 데이터 조회 API 에러

### ISSUE THREAD

**Issue by hyokyungk** [cloud-barista/cb-dragonfly#29]
- CB-Dragonlfy disk 메트릭 조회 시 assignment to entry in nil map 에러 발생

```
cb-dragonfly             | echo: http: panic serving 129.254.175.187:53280: assignment to entry in nil map
cb-dragonfly             | goroutine 2295484 [running]:
cb-dragonfly             | net/http.(*conn).serve.func1(0xc000136320)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1767 +0x139
cb-dragonfly             | panic(0x98f4a0, 0xaee780)
cb-dragonfly             |      /usr/local/go/src/runtime/panic.go:679 +0x1b2
cb-dragonfly             | github.com/cloud-barista/cb-dragonfly/pkg/manager.(*APIServer).GetVMRealtimeMonInfo(0xc000108700, 0xb151a0, 0xc0006186c0, 0xc2d51cb5, 0x58b4daf8b8e663f9)
cb-dragonfly             |      /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/apiserver.go:401 +0x90a
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).add.func1(0xb151a0, 0xc0006186c0, 0xa3f69b, 0x1b)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:505 +0x8a
cb-dragonfly             | github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0xb151a0, 0xc0006186c0, 0x1, 0x1)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/middleware/cors.go:121 +0x477
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0001f8000, 0xb036c0, 0xc0002920e0, 0xc000106100)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:616 +0x22a
cb-dragonfly             | net/http.serverHandler.ServeHTTP(0xc000108540, 0xb036c0, 0xc0002920e0, 0xc000106100)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2802 +0xa4
cb-dragonfly             | net/http.(*conn).serve(0xc000136320, 0xb04e40, 0xc00041a380)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1890 +0x875
cb-dragonfly             | created by net/http.(*Server).Serve
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2927 +0x38e
cb-dragonfly             | echo: http: panic serving 129.254.175.187:53290: assignment to entry in nil map
cb-dragonfly             | goroutine 2297387 [running]:
cb-dragonfly             | net/http.(*conn).serve.func1(0xc0027cf680)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1767 +0x139
cb-dragonfly             | panic(0x98f4a0, 0xaee780)
cb-dragonfly             |      /usr/local/go/src/runtime/panic.go:679 +0x1b2
cb-dragonfly             | github.com/cloud-barista/cb-dragonfly/pkg/manager.(*APIServer).GetVMRealtimeMonInfo(0xc000108700, 0xb151a0, 0xc000618870, 0xd8a111e, 0x6d79c3302fa41783)
cb-dragonfly             |      /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/apiserver.go:401 +0x90a
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).add.func1(0xb151a0, 0xc000618870, 0xa3f69b, 0x1b)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:505 +0x8a
cb-dragonfly             | github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0xb151a0, 0xc000618870, 0x1, 0x1)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/middleware/cors.go:121 +0x477
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0001f8000, 0xb036c0, 0xc0001087e0, 0xc002749800)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:616 +0x22a
cb-dragonfly             | net/http.serverHandler.ServeHTTP(0xc000108540, 0xb036c0, 0xc0001087e0, 0xc002749800)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2802 +0xa4
cb-dragonfly             | net/http.(*conn).serve(0xc0027cf680, 0xb04e40, 0xc002739e80)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1890 +0x875
cb-dragonfly             | created by net/http.(*Server).Serve
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2927 +0x38e
cb-dragonfly             | echo: http: panic serving 129.254.175.187:53275: assignment to entry in nil map
cb-dragonfly             | goroutine 2294723 [running]:
cb-dragonfly             | net/http.(*conn).serve.func1(0xc000593a40)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1767 +0x139
cb-dragonfly             | panic(0x98f4a0, 0xaee780)
cb-dragonfly             |      /usr/local/go/src/runtime/panic.go:679 +0x1b2
cb-dragonfly             | github.com/cloud-barista/cb-dragonfly/pkg/manager.(*APIServer).GetVMRealtimeMonInfo(0xc000108700, 0xb151a0, 0xc000618750, 0xc9ec363, 0x293a46a11aabfae7)
cb-dragonfly             |      /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/apiserver.go:401 +0x90a
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).add.func1(0xb151a0, 0xc000618750, 0xa3f69b, 0x1b)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:505 +0x8a
cb-dragonfly             | github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0xb151a0, 0xc000618750, 0x1, 0x1)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/middleware/cors.go:121 +0x477
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0001f8000, 0xb036c0, 0xc000108380, 0xc000294600)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:616 +0x22a
cb-dragonfly             | net/http.serverHandler.ServeHTTP(0xc000108540, 0xb036c0, 0xc000108380, 0xc000294600)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2802 +0xa4
cb-dragonfly             | net/http.(*conn).serve(0xc000593a40, 0xb04e40, 0xc0005cecc0)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1890 +0x875
cb-dragonfly             | created by net/http.(*Server).Serve
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2927 +0x38e
cb-dragonfly             | echo: http: panic serving 129.254.175.187:53291: assignment to entry in nil map
cb-dragonfly             | goroutine 2297578 [running]:
cb-dragonfly             | net/http.(*conn).serve.func1(0xc000592140)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1767 +0x139
cb-dragonfly             | panic(0x98f4a0, 0xaee780)
cb-dragonfly             |      /usr/local/go/src/runtime/panic.go:679 +0x1b2
cb-dragonfly             | github.com/cloud-barista/cb-dragonfly/pkg/manager.(*APIServer).GetVMRealtimeMonInfo(0xc000108700, 0xb151a0, 0xc0006181b0, 0x6cef9418, 0x7ec36b3af7042e29)
cb-dragonfly             |      /go/src/github.com/cloud-barista/cb-dragonfly/pkg/manager/apiserver.go:401 +0x90a
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).add.func1(0xb151a0, 0xc0006181b0, 0xa3f69b, 0x1b)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:505 +0x8a
cb-dragonfly             | github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0xb151a0, 0xc0006181b0, 0x1, 0x1)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/middleware/cors.go:121 +0x477
cb-dragonfly             | github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0001f8000, 0xb036c0, 0xc0001080e0, 0xc002748d00)
cb-dragonfly             |      /go/src/github.com/cloud-barista/pkg/mod/github.com/labstack/echo/v4@v4.1.10/echo.go:616 +0x22a
cb-dragonfly             | net/http.serverHandler.ServeHTTP(0xc000108540, 0xb036c0, 0xc0001080e0, 0xc002748d00)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2802 +0xa4
cb-dragonfly             | net/http.(*conn).serve(0xc000592140, 0xb04e40, 0xc00041a200)
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:1890 +0x875
cb-dragonfly             | created by net/http.(*Server).Serve
cb-dragonfly             |      /usr/local/go/src/net/http/server.go:2927 +0x38e
cb-dragonfly-influxdb    | [httpd] 172.18.0.4 - cbmon [13/Jul/2020:12:59:18 +0000] "POST /write?consistency=&db=cbmon&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" a9b8cbb2-c508-11ea-8784-0242ac120003 2810
```

**Comment by hyokyungk** [comment]
#30 PR 해당 버그 hotfix 적용
